[profile.default]
src = "src"
out = "out"
libs = [
    "lib",
    "node_modules",
]
remappings = [
    "@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/",
    "erc4626-tests/=lib/openzeppelin-contracts/lib/erc4626-tests/",
    "forge-std/=lib/openzeppelin-contracts/lib/forge-std/src/",
    "halmos-cheatcodes/=lib/openzeppelin-contracts/lib/halmos-cheatcodes/src/",
    "openzeppelin-contracts/=lib/openzeppelin-contracts/",
]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/zmVMGA4CIv6YcpUIDSJWz"
sepolia = "https://eth-sepolia.g.alchemy.com/v2/zmVMGA4CIv6YcpUIDSJWz"